### ISSUE TITLE
v1.1.1 Citizens Error

### ISSUE THREAD

**Issue by jayofearth** [TonimatasDEV/PerWorldPlugins#12]
I know this is a Citizens Error but it only occurs if I update the PWP plugin. If I roll the plugin back to v1.0.1.9 the error does not occur.

```
17.01 08:07:43 [Server] ERROR Unhandled exception occurred in onPacketSending(PacketEvent) for Citizens
17.01 08:07:43 [Server] INFO java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:138) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler.getWorld(Unknown Source) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener.getNPCFromPacket(ProtocolLibListener.java:142) ~[Citizens-2.0.30-b2856.jar:?]
17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener.access$200(ProtocolLibListener.java:37) ~[Citizens-2.0.30-b2856.jar:?]
17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener$2.onPacketSending(ProtocolLibListener.java:97) ~[Citizens-2.0.30-b2856.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
17.01 08:07:43 [Server] INFO at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:332) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:262) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:1614) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:1527) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:1207) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:918) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2559) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2498) ~[?:?]
17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:265) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1240) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1310) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:583) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1005) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-356]
17.01 08:07:43 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
17.01 08:07:43 [Server] ERROR Parameters: 
17.01 08:07:43 [Server] INFO net.minecraft.network.protocol.game.PacketPlayOutEntityHeadRotation@37ec2728[
17.01 08:07:43 [Server] INFO a=377
17.01 08:07:43 [Server] INFO b=-128
17.01 08:07:43 [Server] INFO ]
```

**Comment by TonimatasDEV** [comment]
> ethod getWorld is not supported for temporary players.

You have the latest version of Citizens? [https://ci.citizensnpcs.co/job/Citizens2/](https://ci.citizensnpcs.co/job/Citizens2/)

**Comment by TonimatasDEV** [comment]
> I know this is a Citizens Error but it only occurs if I update the PWP plugin. If I roll the plugin back to v1.0.1.9 the error does not occur.
> 
> ```
> 17.01 08:07:43 [Server] ERROR Unhandled exception occurred in onPacketSending(PacketEvent) for Citizens
> 17.01 08:07:43 [Server] INFO java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:138) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler.getWorld(Unknown Source) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener.getNPCFromPacket(ProtocolLibListener.java:142) ~[Citizens-2.0.30-b2856.jar:?]
> 17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener.access$200(ProtocolLibListener.java:37) ~[Citizens-2.0.30-b2856.jar:?]
> 17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener$2.onPacketSending(ProtocolLibListener.java:97) ~[Citizens-2.0.30-b2856.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:332) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:262) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:1614) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:1527) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:1207) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:918) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2559) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2498) ~[?:?]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:265) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1240) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1310) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:583) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1005) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
> 17.01 08:07:43 [Server] ERROR Parameters: 
> 17.01 08:07:43 [Server] INFO net.minecraft.network.protocol.game.PacketPlayOutEntityHeadRotation@37ec2728[
> 17.01 08:07:43 [Server] INFO a=377
> 17.01 08:07:43 [Server] INFO b=-128
> 17.01 08:07:43 [Server] INFO ]
> ```

You have the latest version of Citizens? https://ci.citizensnpcs.co/job/Citizens2/

**Comment by TonimatasDEV** [comment]
![NVIDIA_Share_3J8quCB425](https://user-images.githubusercontent.com/79017964/212921258-cde1f1c1-5159-4c79-84bd-86b3eebebabd.png)

**Comment by TonimatasDEV** [comment]
> I know this is a Citizens Error but it only occurs if I update the PWP plugin. If I roll the plugin back to v1.0.1.9 the error does not occur.
> 
> ```
> 17.01 08:07:43 [Server] ERROR Unhandled exception occurred in onPacketSending(PacketEvent) for Citizens
> 17.01 08:07:43 [Server] INFO java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:138) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler.getWorld(Unknown Source) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener.getNPCFromPacket(ProtocolLibListener.java:142) ~[Citizens-2.0.30-b2856.jar:?]
> 17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener.access$200(ProtocolLibListener.java:37) ~[Citizens-2.0.30-b2856.jar:?]
> 17.01 08:07:43 [Server] INFO at net.citizensnpcs.ProtocolLibListener$2.onPacketSending(ProtocolLibListener.java:97) ~[Citizens-2.0.30-b2856.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:332) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:262) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:1614) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:1527) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:1207) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:918) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2559) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2498) ~[?:?]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:265) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1240) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1310) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:583) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1005) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-356]
> 17.01 08:07:43 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
> 17.01 08:07:43 [Server] ERROR Parameters: 
> 17.01 08:07:43 [Server] INFO net.minecraft.network.protocol.game.PacketPlayOutEntityHeadRotation@37ec2728[
> 17.01 08:07:43 [Server] INFO a=377
> 17.01 08:07:43 [Server] INFO b=-128
> 17.01 08:07:43 [Server] INFO ]
> ```

Foxed in 1.1.2
