### ISSUE TITLE
Fix bug

### ISSUE THREAD

**Issue by soypeto** [TonimatasDEV/PerWorldPlugins#13]
Hello bro, how are you, sorry for bothering you so much, I still have problems with the plugin, now I have a certain incompatibility with the nlogin plugin, every time I enter it works, but it has an effect on me in the survival world, with the previous version that did not happen to me now with the current one yes, could you help me please?

by the way you can give me your discord to contact you anything.

**Comment by TonimatasDEV** [comment]
> Hello bro, how are you, sorry for bothering you so much, I still have problems with the plugin, now I have a certain incompatibility with the nlogin plugin, every time I enter it works, but it has an effect on me in the survival world, with the previous version that did not happen to me now with the current one yes, could you help me please?
> 
> by the way you can give me your discord to contact you anything.

The discord link: https://discord.com/invite/vWBP4P4Yd8

**Comment by TonimatasDEV** [comment]
> 

Can you pass me the plugin page?

**Comment by TonimatasDEV** [comment]
> Hello bro, how are you, sorry for bothering you so much, I still have problems with the plugin, now I have a certain incompatibility with the nlogin plugin, every time I enter it works, but it has an effect on me in the survival world, with the previous version that did not happen to me now with the current one yes, could you help me please?
> 
> by the way you can give me your discord to contact you anything.

Can you send me the plugin page?

**Comment by soypeto** [comment]
https://www.nickuc.com/es/#plugins

That is the official page, the plugin is called nlogin, the plugin works but when the user enters the server the plugin gives him an effect of not moving for security, what happens is that in the world that has it by default, which is survival, it remains with the effect and it cannot be moved, in previous versions this problem did not happen and I hope you have understood me if I cannot send you a video to discord.

**Comment by TonimatasDEV** [comment]
Solved on Discord.
