### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by ARDragssss** [TonimatasDEV/PerWorldPlugins#15]
my config.yml just keeps reseting every time i restart the server. heres my config:
https://mclo.gs/i4Ir5D2

heres my log:
https://mclo.gs/i4Ir5D2

i also realized in logs that its telling me to download 1.2.0 even tho i downloaded it from here and got this jar:
[PerWorldPlugins-1.2.0.zip](https://github.com/TonimatasDEV/PerWorldPlugins/files/10494850/PerWorldPlugins-1.2.0.zip)

**Comment by TonimatasDEV** [comment]
Fixed in the last version: https://www.spigotmc.org/resources/perworldplugins.96161/
