### ISSUE TITLE
I get this error for no reason and it spams and takes a lot of resources of the server

### ISSUE THREAD

**Issue by Sowadop** [TonimatasDEV/PerWorldPlugins#16]
![Screenshot_20230127-131740~2](https://user-images.githubusercontent.com/104836161/215039768-1737ac78-d8ea-4949-bd07-2ec125540c57.png)

**Comment by TonimatasDEV** [comment]
> ![Screenshot_20230127-131740~2](https://user-images.githubusercontent.com/104836161/215039768-1737ac78-d8ea-4949-bd07-2ec125540c57.png)

This is not my error, it is SimpleLobby's, please use /sl setspawn to define a spawn if you want this error to not appear
