### ISSUE TITLE
Opción de "blacklist"

### ISSUE THREAD

**Issue by AlexCraft1254** [TonimatasDEV/PerWorldPlugins#17]
Utilizar la opción "blacklist:" en true o false, siempre estará como en true (bloqueando por mundos establecidos), ¿esa opción funciona para otra función?

**Comment by TonimatasDEV** [comment]
> Utilizar la opción "blacklist:" en true o false, siempre estará como en true (bloqueando por mundos establecidos), ¿esa opción funciona para otra función?

No, debería funcionar para los mundos, lo voy a revisar.
