### ISSUE TITLE
new issue with perworldplugins - plugin messages not appear

### ISSUE THREAD

**Issue by games4681** [TonimatasDEV/PerWorldPlugins#21]
Hello plugin creator or anyone reading this,
I tried the latest version you posted on Spigot and I'm happy to say that the bug in Essentials chat has been fixed!

But there is a new bug now on my server that you should check:
Every time when you do a command in the plugins, it just doesn't register anything, but if you execute the command, it working but not doesn't register anything in the chat, take an example: I updated someone on luckperms, I don't see a message about it in the chat
I create an NPC in citizens and it doesn't register anything either

I would appreciate it if you could update me about this problem!

**Comment by TonimatasDEV** [comment]
This problem is not caused by my plugin.
