### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by FlaviusAnton26** [TonimatasDEV/PerWorldPlugins#22]
So i wanna make a OneServer With OneBlock,Earth and Boxpvp and i put 3 plugins with Kit.I disabled the first plugin in Boxpvp,2 in Oneblock and 3 in Earth.I wanted to disable each plugin for each world, but when I gave the /kit command it didn't work. For example, the EasyKits plugin was disabled on BoxPvp and Oneblock and was enabled on Survival, although it still said it was disabled. Why?
Can you help me
And the Discord Link is invalid
I wanna make a PerWorldKits if you know

**Comment by TonimatasDEV** [comment]
> 

PerWorldPlugins is not recomended for modalities server.
