### ISSUE TITLE
I'm having trouble running the plugin on my server

### ISSUE THREAD

**Issue by Elabrax** [TonimatasDEV/PerWorldPlugins#23]
Can you make the plugin work for hybrid versions like mohist?

**Comment by TonimatasDEV** [comment]
> Can you make the plugin work for hybrid versions like mohist?

The plugin works correctly in Spigot/Paper, this must be their problem.

**Comment by TonimatasDEV** [comment]
> Can you make the plugin work for hybrid versions like mohist?

Fixed: [PerWorldPlugins-1.4.9.zip](https://github.com/TonimatasDEV/PerWorldPlugins/files/13412285/PerWorldPlugins-1.4.9.zip)
