### ISSUE TITLE
Essentials /help command not working as intended.  (Only /help)

### ISSUE THREAD

**Issue by MadAstro1** [TonimatasDEV/PerWorldPlugins#24]
It looks like the PerWorldPlugins has created an issue with the /help command.  Every other essentials command is working fine except for /help.  I removed the plugin from my server and /help worked as intended.  The error I'm getting after typing /help looks like this below. 

![image](https://github.com/TonimatasDEV/PerWorldPlugins/assets/20710603/4ea1544d-ee9f-4af0-b933-971dcb9283d2)

I am unable to find any errors at all.  Not sure what other information you may need from me to assist with the troubleshooting.  Let me know and I'll do my best to provide as much information as possible.  Also, here's someone else that believed it was an issue with the Essentials plugin itself and created a github issue on their page.

https://github.com/EssentialsX/Essentials/issues/5587

Thanks,

**Comment by TonimatasDEV** [comment]
> It looks like the PerWorldPlugins has created an issue with the /help command. Every other essentials command is working fine except for /help. I removed the plugin from my server and /help worked as intended. The error I'm getting after typing /help looks like this below.
> 
> ![image](https://private-user-images.githubusercontent.com/20710603/287127480-4ea1544d-ee9f-4af0-b933-971dcb9283d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDk4ODMsIm5iZiI6MTcwMTQ0OTU4MywicGF0aCI6Ii8yMDcxMDYwMy8yODcxMjc0ODAtNGVhMTU0NGQtZWU5Zi00YWYwLWI5MzMtOTcxZGNiOTI4M2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE2NTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZjlhNTJhNjY4M2Y1YjhkMGY2MDdlODI0YTNmNzk0ODdkMGUzMWNmMzRkMDNmZjg3M2JiY2JjZjk1YzRmYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dhlZkTF_xS0Ta7rNL7P255Dh6Y2T3qKHoNLJleFlo0g)
> 
> I am unable to find any errors at all. Not sure what other information you may need from me to assist with the troubleshooting. Let me know and I'll do my best to provide as much information as possible. Also, here's someone else that believed it was an issue with the Essentials plugin itself and created a github issue on their page.
> 
> [EssentialsX/Essentials#5587](https://github.com/EssentialsX/Essentials/issues/5587)
> 
> Thanks,

**Fixed:** [PerWorldPlugins-1.5.0.zip](https://github.com/TonimatasDEV/PerWorldPlugins/files/13530060/PerWorldPlugins-1.5.0.zip)
