### ISSUE TITLE
All of my plugins can't run any commands.

### ISSUE THREAD

**Issue by Nihilanthyc** [TonimatasDEV/PerWorldPlugins#25]
I'm running the latest version of PwP, but even the 1.4.8 was giving me these errors, please help me.

https://mclo.gs/3ebdn0w

**Comment by TonimatasDEV** [comment]
> I'm running the latest version of PwP, but even the 1.4.8 was giving me these errors, please help me.
> 
> https://mclo.gs/3ebdn0w

**Test this and send me the new logs** [PerWorldPlugins-1.5.1.zip](https://github.com/TonimatasDEV/PerWorldPlugins/files/13548157/PerWorldPlugins-1.5.1.zip)

**Comment by Nihilanthyc** [comment]
Sorry for beeing a bit late, but I had to pay the host first. Here is another log with the 1.5.1. Same problem...

https://mclo.gs/OkWzHZV

**Comment by TonimatasDEV** [comment]
> Sorry for beeing a bit late, but I had to pay the host first. Here is another log with the 1.5.1. Same problem...
> 
> https://mclo.gs/OkWzHZV

**Fixed:** [PerWorldPlugins-1.5.1.1-dev.zip](https://github.com/TonimatasDEV/PerWorldPlugins/files/13588710/PerWorldPlugins-1.5.1.1-dev.zip)
