### ISSUE TITLE
the plugins but in error the lands plugin

### ISSUE THREAD

**Issue by MaxifeuxG** [TonimatasDEV/PerWorldPlugins#27]
the perworldplugin prevents the lands plugin from working correctly without giving us an error

plugin link::https://www.spigotmc.org/resources/lands-⭕-land-claim-plugin-✅-grief-prevention-protection-gui-management-nations-wars-1-20-support.53313/

**Comment by TonimatasDEV** [comment]
> the perworldplugin prevents the lands plugin from working correctly without giving us an error
> 
> plugin link::[https://www.spigotmc.org/resources/lands-⭕-land-claim-plugin-✅-grief-prevention-protection-gui-management-nations-wars-1-20-support.53313/](https://www.spigotmc.org/resources/lands-%E2%AD%95-land-claim-plugin-%E2%9C%85-grief-prevention-protection-gui-management-nations-wars-1-20-support.53313/)

Its a premium plugin, I don't buy it. Please send a log or I will close this issue

**Comment by MaxifeuxG** [comment]
there is no error just the plugin commands do not work

I will send you the video of the problem
https://cdn.discordapp.com/attachments/1225527564018126988/1230637049296457759/Desktop_04-18-2024_23-50-09-197.mp4?ex=662ccad0&is=662b7950&hm=8479b18061f27fb8e7697e8be30923fe02d8b0e28f8de63201b718b6ffd3d2eb&

**Comment by TonimatasDEV** [comment]
> there is no error just the plugin commands do not work
> 
> I will send you the video of the problem https://cdn.discordapp.com/attachments/1225527564018126988/1230637049296457759/Desktop_04-18-2024_23-50-09-197.mp4?ex=662ccad0&is=662b7950&hm=8479b18061f27fb8e7697e8be30923fe02d8b0e28f8de63201b718b6ffd3d2eb&

Is a premium plugin I can't fix it. I recommend you make a network.

**Comment by MaxifeuxG** [comment]
.+great if we solve the problem just by closing the tickets I understand why the plugin "has no problem"

**Comment by TonimatasDEV** [comment]
@MaxifeuxG I can't understand how people ask for support thinking that I have all the Spigot plugins purchased so I can try them. Don't close it as fixed, but as unplanned
