### ISSUE TITLE
[add]Can you add the functionality for regex (regular expression) recognition of world names?

### ISSUE THREAD

**Issue by lipind** [TonimatasDEV/PerWorldPlugins#28]
Because some plugins will temporarily create a world, 
like worldname：
      Awolrd-213nhkjih
      Awolrd-987h765

I hope to also disable a certain plugin in these worlds

Can you add regex recognition to the world name？

**Comment by TonimatasDEV** [comment]
> Because some plugins will temporarily create a world, like worldname： Awolrd-213nhkjih Awolrd-987h765
> 
> I hope to also disable a certain plugin in these worlds
> 
> Can you add regex recognition to the world name？

Sorry, now I can't. But if you can wait 3 or 4 weeks.
**Reason:**
![image](https://github.com/TonimatasDEV/PerWorldPlugins/assets/79017964/c5bbf3d2-525d-49c7-b967-253d78a578c6)

**Comment by lipind** [comment]
I'm not in a hurry
Hope you recover soon：）

**Comment by TonimatasDEV** [comment]
@lipind Now you can use in the config:
- 'world_*'
- '*_nether'

It blocks all worlds started with "world_" and all finished with '_nether'. It is good for you?

Here is the file for testing:
[PerWorldPlugins-1.5.5.zip](https://github.com/user-attachments/files/16126385/PerWorldPlugins-1.5.5.zip)
