### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by coolcostupit** [TonimatasDEV/PerWorldPlugins#5]
Add a revert value in the config file that will revert their way of disabling plugins pw. Ex:

  PerWorldInventory:
  - world
  
  perworldinventory will now only work in "world" if revert is true

**Comment by TonimatasDEV** [comment]
It is a good idea

**Comment by TonimatasDEV** [comment]
> i need this too

Sorry, I don't have time for this. Wait a while

**Comment by TonimatasDEV** [comment]
I've put it on the list of things to add
