### ISSUE TITLE
HeadDatabase & Luckperms prefix not working

### ISSUE THREAD

**Issue by aksyttt** [TonimatasDEV/PerWorldPlugins#7]
I cannot get heads from Headdatabase plugin & luckperms group prefix are not showing in front of name

**Comment by MiauDona** [comment]
> 

Compatibility with too weighted plugins is too complex. We have no intention to fix this anytime soon. Try using another plugin

**Comment by TonimatasDEV** [comment]
> I cannot get heads from Headdatabase plugin & luckperms group prefix are not showing in front of name

As MeowDona says I can't add compatibility with those plugins since their program is very complex
