### ISSUE TITLE
Incompatibilty with Screaming Bedwars plugin and anti cooldown plugin

### ISSUE THREAD

**Issue by coolcostupit** [TonimatasDEV/PerWorldPlugins#8]
![image](https://user-images.githubusercontent.com/85961554/207067080-d6a829ec-3678-4a2b-9af9-765250d9e7b2.png)
The PerWorldPlugins plugin makes every item in the shop from villagers unbuyable and also enabled hit cooldown meanwhile I have a anticooldown plugin which usually disables it. Also here is a dev's response:
![image](https://user-images.githubusercontent.com/85961554/207067414-6ef01619-d639-4ab7-b8e7-9e0a80a414b9.png)
Please fix this.

**Comment by MiauDona** [comment]
Hello, @coolcostupit 
Could you tell the name of the plugins which you have issues?

**Comment by TonimatasDEV** [comment]
> @MiauDona what now? And why isnt the dev responding?

Sorry, test this version:
[PerWorldPlugins-1.0.3.zip](https://github.com/TonimatasDEV/PerWorldPlugins/files/10252078/PerWorldPlugins-1.0.3.zip)

**Comment by MiauDona** [comment]
> @TonimatasDEV still having the same issues, nothing changed... what do I have to do now?

We're sorry. We can't fix this issue right now. The plugin cannot do such things as divide the same server in different complete minigames right now. In a long term maybe we'll fix it but so far we have not found out the solution. At least we recommend u to do a network. This will allow u to do what u want better.
